' Developer Express Code Central Example:
' How to delete grid rows via the DeleteFocusedRow grid command
' 
' The following example demonstrates how to add a Delete item to the grid cell's
' context menu.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E1791
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace GridCommands_DeleteFocusedRow.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As GridCommands_DeleteFocusedRow.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New GridCommands_DeleteFocusedRow.Properties.Settings())), GridCommands_DeleteFocusedRow.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return GridCommands_DeleteFocusedRow.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
